# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3
import finalMain


class Ui_jobSeekerLogin(object):
    def returnToMain(self):
        self.window1 = QtWidgets.QMainWindow()
        self.secondUI = finalMain.Ui_FirstWindow()
        self.secondUI.setupUi(self.window1)
        self.window1.show()


    def setupUi(self, jobSeekerLogin):
        jobSeekerLogin.setObjectName("jobSeekerLogin")
        jobSeekerLogin.resize(1200, 750)
        jobSeekerLogin.setStyleSheet("background-color:#fff;")
        self.centralwidget = QtWidgets.QWidget(jobSeekerLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(160, 190, 361, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.userbame = QtWidgets.QLineEdit(self.groupBox)
        self.userbame.setGeometry(QtCore.QRect(140, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.userbame.setFont(font)
        self.userbame.setObjectName("userbame")
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(140, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.login = QtWidgets.QPushButton(self.groupBox)
        self.login.setGeometry(QtCore.QRect(220, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color: #5AAA78;\n"
"border:none;\n"
"color:lightgray;\n"
"")
        self.login.setObjectName("login")
        self.cancel = QtWidgets.QPushButton(self.groupBox)
        self.cancel.setGeometry(QtCore.QRect(140, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("background-color: #105687;\n"
"border:none;\n"
"color:lightgray;\n"
"")
        self.cancel.setObjectName("cancel")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(0, 0, 1201, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("background-color: #5AAA78;\n"
"border:none;\n"
"color:#fff;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 180, 461, 381))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/unnamed.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        jobSeekerLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(jobSeekerLogin)
        QtCore.QMetaObject.connectSlotsByName(jobSeekerLogin)

    def retranslateUi(self, jobSeekerLogin):
        _translate = QtCore.QCoreApplication.translate
        jobSeekerLogin.setWindowTitle(_translate("jobSeekerLogin", "MainWindow"))
        self.groupBox.setTitle(_translate("jobSeekerLogin", "Job Seeker  Login Form"))
        self.label.setText(_translate("jobSeekerLogin", "Username"))
        self.label_2.setText(_translate("jobSeekerLogin", "Password"))
        self.login.setText(_translate("jobSeekerLogin", "login"))
        self.cancel.setText(_translate("jobSeekerLogin", "cancel"))
        self.lblTitle.setText(_translate("jobSeekerLogin", "Welocme to Employment Application Software"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jobSeekerLogin = QtWidgets.QMainWindow()
    ui = Ui_jobSeekerLogin()
    ui.setupUi(jobSeekerLogin)
    jobSeekerLogin.show()
    sys.exit(app.exec_())
